### ISSUE TITLE
[Feature Request] Keep distant meshes when quitting a server

### ISSUE THREAD

**Issue by JustAGenericUser** [MCRcortex/nvidium#168]
I think its a big downside that meshes are lost when quitting a world, especially a server, requiring you to revisit every chunk you want to see. Therefore I would like to have the meshes dumped to a file when quitting/changing dimension on a server (or singleplayer world) or at least kept in the GPU, as long as no other world is opened or the game closed. 
I don't know if this is viable in this mod, but as I found no other issue or mention of this idea, I just want to put it out there.

**Comment by flipfloppy1** [comment]
The only problem I can see with this is file size.
A 128 chunk render distance can be up to ~10gb in vram, and that would definitely add up between worlds if you’re saving it to disk. You’d probably be better off using bobby or something similar which caches the chunks themselves client-side with all the compression things they have going for them, especially since meshing is so fast with nvidium.

**Comment by KarmaMarazu** [comment]
Use a mod like bobby, voxy or DH
