### ISSUE TITLE
amd gpu

### ISSUE THREAD

**Issue by CephandriusMaxtori** [MCRcortex/nvidium#187]
some amd gpus support opengl so plz.

**Comment by Taiyou06** [comment]
AMD has to add the feature themselves to the driver. There's nothing that nvidium/mod dev can do. I would suggest you to check the already opened issues about these and close this one.

**Comment by Andarwinux** [comment]
AMD does support mesh shader and OpenGL, all you have to do is register a company, pay $22,000 a year to KHR for "Full working group participation and voting rights", then draft a OpenGL cross-vendor mesh shader proposal, pray that KHR doesn't ignore your proposal, and then wait for a few years for the proposal to pass, it's very simple, just go and do it now.

**Comment by ichijiyujin** [comment]
> some amd gpus support opengl so plz.

@Ngbcoder Let me make things clear. Most GPUs support OpenGL. That's not the issue, nor the specific requirement for this mod to work. This mod uses a GPU feature called "mesh shaders". Personally, I have no idea what that is, but here's what I know. This feature is not a standard feature for the OpenGL API. It's not something that manufacturers need to put either in their GPUs or their drivers to have their hardware be considered fully OpenGL compliant. So companies have no incentive to include support for this, and AMD has other things to work on, than worrying about 1 fringe mod that is trying to use a niche feature in an API that is barely used in modern gaming. The only reason this mod even exists is because Nvidia decided to add this for reasons we don't know. It's pretty much one big fluke. 

As for AMD and mesh shader support in general. It is true that AMD cards are indeed capable of using mesh shaders in the Vulkan API, which, as you likely know, Minecraft does not support out of the box. Your best bet is to check the VulkanMod, see how it performs for you, and see what their plans are for the future. As it stands, and for the foreseeable future, there is simply no point in asking for AMD support from Nvidium. It will not happen and it is out of the control of the people here.

**Comment by CephandriusMaxtori** [comment]
thanks. i did not know that.

**Comment by ImBehinYa** [comment]
I opened an issue in AMD's new driver forum on GitHub and already received a response. They are aiming for the end of the year. Maybe you should comment or react so they see that this matters to us.

https://github.com/GPUOpen-Drivers/AMD-Gfx-Drivers/issues/4
