### ISSUE TITLE
[Idea] Use cuRAND in place of vanilla's RNG when possible

### ISSUE THREAD

**Issue by vico93** [MCRcortex/nvidium#218]
Since it's a mod focused in bringing "cutting edge nvidia features" to Sodium and the game, i thought it would not be bad to ask this idea i had here first before on Fabric's Discord, even this mod being client-side and not messing up with any (integrated) server-side stuff.

Basically, inspired by [KillTheRNG](https://modrinth.com/mod/killtherng) and [Faster Random](https://modrinth.com/mod/faster-random), replace the game's RNG to uses [cuRAND](https://docs.nvidia.com/cuda/curand/index.html) ([examples](https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuRAND)), i think it would do some performance gains to offload such part of the game to the GPU.

**Comment by Earthcomputer** [comment]
I don't know why people think the game's random number generator is that resource intensive. It's a single multiplication and addition, followed by a shift and a mask to get the right bits of the seed. Faster Random actually makes the game's RNG slower because I don't think the guy did any actual benchmarking to prove that his RNG is actually faster. Offloading serial operations like this to the GPU is going to be way slower because transferring information to and from the GPU is already orders of magnitude slower than this simple operation.
