### ISSUE TITLE
Question: Potential support for Embeddium?

### ISSUE THREAD

**Issue by Ra2-IFV** [MCRcortex/nvidium#223]
[Embeddium](https://github.com/embeddedt/embeddium) is a fork of Sodium 0.5.8  
so I guess it's possible to get it working with embeddium?

**Comment by KarmaMarazu** [comment]
There is no reason to as sodium is better on fabric anyways and when sodium releases to neoforge at 6.0 its also gonna be better there for now just use sodium and indium its the same but better

People who use embeddium in their modpack are doing it mostly because of some drama and not cuz of it being better. support the original

**Comment by MCRcortex** [comment]
Embeddedt has done a package rename in 1.21, which means using sinytra connector will most likely no longer work. As for fabric you should probably stick to using sodium. Any future updates to nvidium will continue to be built around sodium and any updates it has.

**Comment by Ra2-IFV** [comment]
Thanks for creating this project.
