### ISSUE TITLE
Renderer starts to corrupt after some amount of geometry

### ISSUE THREAD

**Issue by alexander4308** [MCRcortex/nvidium#244]
170 render distance should be enough to bug it out
![{537896C2-494D-4067-9A81-B6E9937A3763}](https://github.com/user-attachments/assets/11961169-2332-4009-a20d-59dafc569bb6)

**Comment by MCRcortex** [comment]
Upload logs please

**Comment by alexander4308** [comment]
https://mclo.gs/GSGLmMR

**Comment by MCRcortex** [comment]
it appears the issue is [here](https://github.com/MCRcortex/nvidium/commit/646925395979c17785b841b4ac6ea0ef8a7900e2#diff-d256b22efb9bd109264fc181381ea0fbdf53446fd816c0184f27066262ea2f05R69), The maximum index of a quad is 2^28 which gives an effective memory range of ~16-17 gb of vram, 

Thank you for the report, i will look into solutions
