### ISSUE TITLE
a few suggestions to improve draw distance

### ISSUE THREAD

**Issue by ghost** [MCRcortex/nvidium#43]
every time you enter the world, you have to run and load the area to see a large drawing
what is annoying in survival mode

it can be improved
by adding the preservation of loaded terrain
like the bobby mod that creates a folder in the world and saves loaded chunks there visually

also so that in the new world you don’t have to load 128 chunks or more

you can try to implement a pregenerator function that will visually pregenerate nvidium chunks
up to a certain draw value

this will help make the huge draw much more playable

**Comment by BuggyAl** [comment]
Calling the `MinecraftClient.getInstance().worldRenderer.reload()` method will reset the current loaded nvidium chunks. Fixing this would allow for mods such as [VisibleBarriers](https://github.com/AmyMialeeMods/visible-barriers/blob/main/src/main/java/xyz/amymialee/visiblebarriers/VisibleBarriers.java#L62) to function properly.

**Comment by zwamdurkel** [comment]
This is the main thing still missing from this mod. Please add a way to cache previously loaded chunks between sessions (restarting/changing dimension) such that the "Keep Distance" loads these chunks again. 

I play with "Keep all" and my computer can handle it no problem, but every time I go to the nether and back, the kept chunks are reset, presumably because of the function mentioned here https://github.com/MCRcortex/nvidium/issues/43#issuecomment-1636621246

**Comment by MCRcortex** [comment]
with 0.2 you can use bobby pretty efficiently to load the chunks back

**Comment by MikiP98** [comment]
There is a big performance loss when bobby is enabled [issue](https://github.com/Johni0702/bobby/issues/151), so if NVIDIUM could add something like this, it would be awesome.

**Comment by MCRcortex** [comment]
Pregenerator is not planned nor is implementing a bobby like cache at the present time
