### ISSUE TITLE
[Suggestion] Chunk remembering

### ISSUE THREAD

**Issue by antieksi** [MCRcortex/nvidium#87]
«Region Keep Distance» would work even better if it would remember all the explored chunks, and load them each time you join world or server again. 

And thanks for the mod, it works flawlessly on my GTX 1650 Ti.

**Comment by Ivanmatthew** [comment]
I am not sure what you mean by this, but chunk memory is already provided by the server. Since Nvidium is a rendering pipeline, all it does is render what needs to be rendered, you'd need to use a separate mod to do this. You'd be better off asking this to the developers of Sodium. It might be viable if you have fast enough file storage to keep up with chunk loading demand (e.g. with DirectStorage tech), but it's really not viable for the effort that needs to be taken (probably, correct me if I'm wrong.)

**Comment by EquityX** [comment]
I believe they are asking for something like this https://github.com/Johni0702/bobby to be implemented into this mod. That mod also has an option to not render any entities in fake chunks which has a massive performance impact.

**Comment by antieksi** [comment]
Sorry for the inactivity.
I've figured out that Bobby's extra rendered chunks feature actually works with Nvidium and doesn't lag the game at all. However, there is one small issue: fog can't be set to more than 32 chunks (atleast in Sodium), and I don't think that it's what Nvidium is supposed to do. There aren't any mods that do that though.

**Comment by antieksi** [comment]
Looks like I'm making things up, also sorry for that. There is no extra rendered chunks feature in Bobby, but there is maximum rendered chunks, and this number is practically unlimited. It's pretty much same thing as Nvidium's extra chunks, but they don't just stay if they were loaded at any moment; they load the same time I join world or server. Fog issue persists.

**Comment by Felix14-v2** [comment]
Just disable the fog using Sodium Extra. Also you can override the view distance limit by increasing its value in the C2ME mod config file.

**Comment by FASTB1mc** [comment]
I find that C2ME actually makes my FPS lower whenever I use it and it uses a lot of memory when I put it on my Minecraft server.

**Comment by FASTB1mc** [comment]
Also the Bobby mod and Voxy mod (made by Cortex) have features that do chunk remembering but it takes up space on your computer. In Bobby the future is called Single player view distance (I think), and I don't know about Voxy though.
