### ISSUE TITLE
Game ignores keyboard input

### ISSUE THREAD

**Issue by KeeveeKoomoo** [MCRcortex/nvidium#92]
if I go into a world/server with nvidium enabled the game ignores any keyboard input. to fix this I can disable nvidium in the settings, open the world, and then re-enable the setting, but obviously that's still an issue because it's just a hassle

**Comment by Tethanol** [comment]
I'm also having the same issue here. When you reenable Nvidium, does the border fog look black? I noticed when I disable, load in, then reenable, the fog is black, and farther chunks fade into black for whatever reason.

**Comment by ZekIzLoupriora** [comment]
I think I might have a solution for that problem. In my case (minecraft 1.20.1) I found out that the mod Fast Load is causing the issue, because it preloads chunks or something and, as I found out, causes other mods and player movement to not load/register for some time after loading into a world. I think that this particular behaviour is causing issues, because nvidium is rendering chunks in it's own way. I hope this helps!

**Comment by Briarbot2011** [comment]
i'm having issues with this too, i'm running minecraft 1.20.1 with 102 mods with a nvidia geforce rtx 2060 GPU and amd ryzen 3 2200g CPU

**Comment by MCRcortex** [comment]
This issue is an issue with fastload

**Comment by Briarbot2011** [comment]
> This issue is an issue with fastload

oh my god thank you
